'use strict';

/**
 * pr.js — Open a draft pull request for the agent's fix.
 */

const { getClient }  = require('./client');
const { AGENT_MARKER } = require('./issues');

/**
 * Open a draft PR linking back to the issue.
 *
 * @param {object} opts
 * @param {string} opts.owner
 * @param {string} opts.repo
 * @param {string} opts.branchName     Head branch with the fix
 * @param {string} opts.baseBranch     Target branch (usually main/master)
 * @param {number} opts.issueNumber
 * @param {string} opts.issueTitle
 * @param {string} opts.summary        Agent's description of what was changed
 * @param {string} opts.approach       Reasoning / approach taken
 * @param {Array}  opts.filesChanged
 * @returns {{ url: string, number: number }}
 */
async function openDraftPR({
  owner, repo, branchName, baseBranch,
  issueNumber, issueTitle, summary, approach, filesChanged,
}) {
  const octokit = getClient();

  const title = `fix: ${issueTitle} (closes #${issueNumber})`;

  const body = [
    AGENT_MARKER,
    '',
    `## 🤖 Agent Fix — closes #${issueNumber}`,
    '',
    '> **This is a draft PR generated by the GitHub Task Agent. It requires human review before merging.**',
    '',
    '### Summary',
    summary,
    '',
    '### Approach',
    approach,
    '',
    '### Files changed',
    filesChanged.map(f => `- \`${f}\``).join('\n'),
    '',
    '### Review checklist',
    '- [ ] Code logic is correct',
    '- [ ] Tests pass',
    '- [ ] No unintended side effects',
    '- [ ] Ready to merge',
  ].join('\n');

  const { data } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head:  branchName,
    base:  baseBranch,
    draft: true,
  });

  return { url: data.html_url, number: data.number };
}

/**
 * Detect the default branch (main or master) for a repo.
 */
async function getDefaultBranch(owner, repo) {
  const octokit = getClient();
  const { data } = await octokit.repos.get({ owner, repo });
  return data.default_branch || 'main';
}

module.exports = { openDraftPR, getDefaultBranch };
